apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-front
  labels:
    app: todo-distributed
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-distributed
      component: frontend
  template:
    metadata:
      labels:
        app: todo-distributed
        component: frontend
    spec:
      containers:
        - name: todo-front
          image: lemoncodersbc/lc-todo-front:v5-2024
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
