apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: todo-app
    type: local
spec:
  storageClassName: todo-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  persistentVolumeReclaimPolicy: Retain
