apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: todo-app
    component: database
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      component: database
  template:
    metadata:
      labels:
        app: todo-app
        component: database
    spec:
      containers:
        - name: postgres
          image: lemoncodersbc/lc-todo-monolith-psql:v5-2024
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: DB_NAME

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
