apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app-mem
spec:
  type: LoadBalancer
  selector:
    app: todo-app-mem
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
